### ISSUE TITLE
HSI Data File Structure

### ISSUE THREAD

**Issue by JacCubk** [AstilePeter/HSI-PNG-Semantic-Segmentation-UNet#1]
Hello! 

Thank you for contributing such a great work. 

I'm very interested in it. Unfortunately, I am unable to download the HSI data from the link provided. I hope to use this network to train my own HSI dataset, but as a beginner, I'm unsure about how to prepare the data files. I have a 512ｘ512ｘ101 HSI dataset. 

Could you please guide me on how to prepare the data to make it work? 

Thank you! 
Wish you more success!

**Comment by AstilePeter** [comment]
Hey,

I think you can upscale the number of channels from 101 to 204. Then I think the model will work.

**Comment by JacCubk** [comment]
Thank‘s a lot!
